package uk.ac.hope.csc.hostel.management.system;

import java.time.Month;

public class Payment {

    private double amount;
    private Month month;

    /**
     * The constructor for a Payment object.
     * @param month the month of the yerar for this payment
     * @param amount the amount paid
     */
    public Payment(Month month, double amount) {
        this.month = month;
        this.amount = amount;
    }

    /**
     * Queries the payment object
     * @return the amount in the payment
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Gets the month that a Payment was made
     * @return A java.time.Month value.
     */
    public Month getMonth() {
        return month;
    }

    /**
     * toString() autogenerated methid
     * @return a string JSON representation of this runtime object.
     */
    @Override
    public String toString() {
        return "Payment{" +
                "amount=" + amount +
                ", month=" + month +
                '}';
    }
}
