package uk.ac.hope.csc.hostel.management.system;

import java.io.Serializable;
import java.time.Month;
import java.util.Date;

public class Payment implements Serializable {

    private double amount;
    private Month month;
    private Date date;

    /**
     * The constructor for a Payment object.
     * @param month the month of the year for this payment is made.
     * @param amount the amount paid
     * @param date the date on which the payment was made (not neccessarily in the month).
     */
    public Payment(Month month, double amount, Date date) {
        this.month = month;
        this.amount = amount;
        this.date = date;
    }

    /**
     * Queries the payment object
     * @return the amount in the payment
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Gets the month that a Payment was made
     * @return A java.time.Month value.
     */
    public Month getMonth() {
        return month;
    }

    /**
     *
     * @return
     */
    public Date getDate() {
        return date;
    }

    /**
     * toString() autogenerated method
     * @return a string JSON representation of this runtime object.
     */
    @Override
    public String toString() {
        return "Payment{" +
                "amount=" + amount +
                ", month=" + month +
                ", date=" + date +
                '}';
    }




}
